### PR TITLE
Added iPad icons

### PR DESCRIPTION
**Pull request by samgreen**
Added the 76pt app icons for iOS7 iPad & Retina iPad.

### CODE REVIEW

**Comment by nilnilnil** [comment]
These look blurry.  Is there anything we can do about that?  @micpringle @infinitekind @sreilly I'd like to get this merged and released ASAP.

**Comment by samgreen** [comment]
The largest asset available wasn't as big as needed. If you have the source files only a 152px icon is needed. The other icon was downsized so it should be okay!

**Comment by nilnilnil** [comment]
@infinitekind I think this was prematurely merged.  I made a comment on the original issue with an updated image. https://github.com/duckduckgo/ios/issues/34

**Comment by infinitekind** [comment]
Yes, I'm adding the updated image from that issue to the main branch and will rebuild and submit the update this evening (your afternoon).

**Comment by nilnilnil** [comment]
Cool, thx!

**Pull request merged**
