### PR TITLE
Changes default Readability setting

### LINKED ISSUE #11: all stories not coming through
noticed that I am not seeing all the sources represented by the server on the client

### PR DESCRIPTION
**Pull request by ghost**
Fixes #11

### CODE REVIEW

**Comment by nilnilnil** [comment]
:+1:

**Comment by yegg** [comment]
For people who haven't messed with this before, when the app updates will this magically work and they'll see new stories?

**Comment by ghost** [comment]
@yegg They should do. The defaults aren't written to disk, but instead set at launch.

**Comment by ghost** [comment]
@yegg @nilnilnil 

I have just tried this by first downloading the live App Store version, and then updating to the current TF build. The default switches automatically and any users will then see missing stories.

**Pull request merged**
