### PR TITLE
(#13) Add 'Save to Library' to images from stories

### PR DESCRIPTION
**Pull request by quanganhdo**
34471188-9c0f-11e3-9e2c-fdbb49932254
37769e6e-9c0f-11e3-8609-5047f2b4c820

### CODE REVIEW

**Comment by ghost** [comment]
@quanganhdo That's all from me, at the moment :thumbsup:

**Comment by nilnilnil** [comment]
Will this also work for the search results?  Everything in the UIWebView?

**Comment by ghost** [comment]
I believe so. It injects some Javascript into the rendered web page which returns the URL of the image you tap.

**Comment by quanganhdo** [comment]
@micpringle It should now check for user's permission and notify them accordingly.

**Comment by nilnilnil** [comment]
@micpringle thoughts?

**Comment by ghost** [comment]
@nilnilnil 

This is definitely better.

My only criticism would be that in `image:didFinishSavingWithError:contextInfo:` it's assumed the save failed due to the user denying permission to their camera roll, but there are many reasons a save operation could fail, such as not having enough disk space for example.

**Comment by quanganhdo** [comment]
@micpringle I changed it to display the actual `[error localizedDescription]` now, though sometime it is still cryptic. E.g. disallow the app's access to Photo Library the first time the user saves will return 'data unavailable'.

**Comment by ghost** [comment]
@quanganhdo 

It might be worthwhile taking a look at [writeImageToSavedPhotosAlbum:orientation:completionBlock:](https://developer.apple.com/library/ios/documentation/AssetsLibrary/Reference/ALAssetsLibrary_Class/Reference/Reference.html#//apple_ref/doc/uid/TP40009722-CH1-SW17) and seeing if the error message passed to the block is a little less cryptic.

The other option would be to simply have two branches for the error. If an error has occurred and authorisation is denied (_which can easily be checked_) then throw up the alert asking them to give the app permission. Otherwise throw up a nice friendly alert stating the save failed, and ask them to try again; @nilnilnil might want to jump in provide the actual wording.

**Comment by nilnilnil** [comment]
ping

**Comment by ghost** [comment]
@nilnilnil We'll take a look at this once the visual refresh is complete.

**Comment by nilnilnil** [comment]
I'd like to take a look at this too, but it's not as necessary as https://github.com/duckduckgo/ios/issues/26

**Pull request closed without merging**
